### ISSUE TITLE
FASTA format output

### ISSUE THREAD

**Issue by wodanaz** [rambaut/Seq-Gen#11]
Hi there,
     It was announced that FASTA format output is a new feature in Version 1.3.4 but I can't figure how to set the output parameters to run it. Also, I downloaded version 1.3.4 and  seems to be version  1.3.2x:

Seq-Gen-1.3.4$ seq-gen -h
Sequence Generator - seq-gen
Version 1.3.2x

Cheers,

**Comment by rambaut** [comment]
To get fasta format you do "-o f" (for output fasta).

If it isn't there (and isn't listed in the help) then perhaps you have download v1.3.2. I will check what that issue is.

Andrew

**Comment by rambaut** [comment]
Hi again,

I have checked. The version on github is definitely 1.3.4. I think the problem is that you have v1.3.2 on your path? So when you type 'seq-gen' you get the old version. Try doing 'source/seq-gen' (if that is where the compiled executable is).

A.

**Comment by wodanaz** [comment]
Great, and thanks for the rapid response. I downloaded the tarball version from https://github.com/rambaut/Seq-Gen/archive/1.3.4.tar.gz

After I extracted and installed the program,  the header shows this:

Seq-Gen-1.3.4$ seq-gen -h
Sequence Generator - seq-gen
Version 1.3.2x


Cheers,

**Comment by wodanaz** [comment]
I checked, and its true. I had the old version in my path

Cheers

**Comment by rambaut** [comment]
Sorted.

A.

**Comment by wodanaz** [comment]
Cheers, although it was very intuitive it would be nice to update the documentation html.

Cheers,

**Comment by rambaut** [comment]
Done (on the github version at least).

A.
